fix: just give everything $HOME

diff --git a/overlays/gui-sway/usr/local/bin/flatpak-update b/overlays/gui-sway/usr/local/bin/flatpak-update
--- a/overlays/gui-sway/usr/local/bin/flatpak-update
+++ b/overlays/gui-sway/usr/local/bin/flatpak-update
@@ -3,7 +3,7 @@
 readarray -t apps < <(cat /usr/local/etc/flatpak.d/*)
 
 function flathub_working {
-	flatpak --system remote-info flathub org.signal.Signal >/dev/null 2>&1 || return 1
+    flatpak --system remote-info flathub org.signal.Signal >/dev/null 2>&1 || return 1
 }
 
 TIMEOUT=600
@@ -12,13 +12,13 @@ DURATION=0
 
 echo -n 'Waiting for flathub'
 while ! flathub_working; do
-	if ((DURATION >= TIMEOUT)); then
-		echo "Unable to reach flathub" >&2
-		exit 1
-	fi
-	echo -n .
-	sleep ${STEP}
-	((DURATION += STEP))
+    if ((DURATION >= TIMEOUT)); then
+        echo "Unable to reach flathub" >&2
+        exit 1
+    fi
+    echo -n .
+    sleep ${STEP}
+    ((DURATION += STEP))
 done
 echo
 
@@ -27,3 +27,4 @@ flatpak install --or-update --system --assumeyes --noninteractive --verbose flat
 
 # Set apps to dark mode, if we can
 flatpak override --system --env=GTK_THEME=Materia-dark-compact
+flatpak override --system --filesystem=home
